CREATE DATABASE admilab;

/*Entidades*/

CREATE TABLE admilab.administrador(
  `USUARIO` varchar(50) NOT NULL PRIMARY KEY,
  `CONTRASEÑA` varchar(50) NOT NULL,
  `OBSERVACIONES` mediumtext
);

CREATE TABLE admilab.tecnico(
  `ID_TECNICO` varchar(50) NOT NULL PRIMARY KEY,
  `CONTRASEÑA` varchar(40) NOT NULL,
  `NOMBRE(S)` varchar(50) NOT NULL,
  `P_APELLIDO` varchar(50) NOT NULL,
  `S_APELLIDO` varchar(50) NOT NULL,
  `OBSERVACIONES` mediumtext
);

CREATE TABLE admilab.maestro(
   `ID_MAESTRO` varchar(50) NOT NULL PRIMARY KEY,
   `CONTRASEÑA` varchar(40) NOT NULL,
   `NOMBRE(S)` varchar(50) NOT NULL,
   `P_APELLIDO` varchar(50) NOT NULL,
   `S_APELLIDO` varchar(50) NOT NULL,
   `OBSERVACIONES` mediumtext
);

CREATE TABLE admilab.laboratorio(
  `ID_LABORATORIO` int(3) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `NOMBRE` varchar(50) NOT NULL,
  `OBSERVACIONES` mediumtext
);

CREATE TABLE admilab.materia(
  `ID_MATERIA` varchar(50) NOT NULL PRIMARY KEY,
  `NOMBRE` varchar(50) NOT NULL,
  `DESCRIPCION` varchar(50) NOT NULL,
  `OBSERVACIONES` mediumtext
);

/*Relaciones*/
CREATE TABLE admilab.material(
  `ID_MATERIAL` varchar(50) NOT NULL PRIMARY KEY,
  `USUARIO_ADMIN` varchar(50) NOT NULL,
  `DESCRIPCION` mediumtext NOT NULL,
  `MARCA` varchar(50) NOT NULL,
  `PROVEDOR` varchar(50) NOT NULL,
  `CANTIDAD` varchar(10) NOT NULL,
  `UNIDAD` varchar(50) NOT NULL,
  `FECHA_ENTREGA` date NOT NULL,
  `FECHA_ACTUALIZACION` date NOT NULL,
  `OBSERVACIONES` mediumtext
);

CREATE TABLE admilab.horario(
  `ID_HORARIO` int(5) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `ID_MAESTRO` varchar(50) NOT NULL,
  `ID_LABORATORIO` int(3) NOT NULL,
  `ID_MATERIA` varchar(50) NOT NULL,
  `DIA` varchar(10) NOT NULL,
  `HORA_ENTRADA` time NOT NULL,
  `HORA_SALIDA` time NOT NULL,
  `OBSERVACIONES` mediumtext
);

CREATE TABLE admilab.material_practica(
  `ID_PRACTICA` varchar(50) NOT NULL,
  `ID_MATERIAL` varchar(50) NOT NULL,
  `ID_HORARIO` int(5) NOT NULL,
  `ID_TECNICO` varchar(50) NOT NULL,
  `CANTIDAD_USADA` varchar(10) NOT NULL,
  `UNIDAD` varchar(50) NOT NULL,
  `OBSERVACIONES` mediumtext
);

/*Asiganación keys*/
ALTER TABLE admilab.material
ADD KEY `USUARIO_ADMIN` (`USUARIO_ADMIN`);

ALTER TABLE admilab.horario
ADD KEY `ID_MAESTRO` (`ID_MAESTRO`),
ADD KEY `ID_LABORATORIO` (`ID_LABORATORIO`),
ADD KEY `ID_MATERIA` (`ID_MATERIA`);

ALTER TABLE admilab.material_practica
ADD KEY `ID_MATERIAL` (`ID_MATERIAL`),
ADD KEY `ID_HORARIO` (`ID_HORARIO`),
ADD KEY `ID_TECNICO` (`ID_TECNICO`);

/*Constraints y foreing keys*/
ALTER TABLE admilab.material
ADD CONSTRAINT `FK_USUARIO_ADMIN` FOREIGN KEY (`USUARIO_ADMIN`) REFERENCES `admilab`.`administrador` (`USUARIO`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE admilab.horario
ADD CONSTRAINT `FK_ID_MAESTRO` FOREIGN KEY (`ID_MAESTRO`) REFERENCES `admilab`.`maestro` (`ID_MAESTRO`) ON DELETE CASCADE ON UPDATE CASCADE,
ADD CONSTRAINT `FK_ID_LABORATORIO` FOREIGN KEY (`ID_LABORATORIO`) REFERENCES `admilab`.`laboratorio` (`ID_LABORATORIO`) ON DELETE CASCADE ON UPDATE CASCADE,
ADD CONSTRAINT `FK_ID_MATERIA` FOREIGN KEY (`ID_MATERIA`) REFERENCES `admilab`.`materia` (`ID_MATERIA`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE admilab.material_practica
ADD CONSTRAINT `FK_ID_MATERIAL` FOREIGN KEY (`ID_MATERIAL`) REFERENCES `admilab`.`material` (`ID_MATERIAL`) ON DELETE CASCADE ON UPDATE CASCADE,
ADD CONSTRAINT `FK_ID_HORARIO` FOREIGN KEY (`ID_HORARIO`) REFERENCES `admilab`.`horario` (`ID_HORARIO`) ON DELETE CASCADE ON UPDATE CASCADE,
ADD CONSTRAINT `FK_ID_TECNICO` FOREIGN KEY (`ID_TECNICO`) REFERENCES `admilab`.`tecnico` (`ID_TECNICO`) ON DELETE CASCADE ON UPDATE CASCADE;
